"""
Matriz completa de Governança das Exceções Comerciais e Operacionais.
"""

EXCEPTIONS_RULES = {
    "Exclusividade de fornecimento - Município": {
        "comercial": "Se escola já possui, não precisa de aprovação. Caso seja nova solicitação, acionar Rafael Martinez @triagem psc",
        "comercial_approver": "Rafael Martinez",
        "ops": "-",
        "ops_approver": None,
    },
    "Exclusividade de fornecimento - Região": {
        "comercial": "Se escola já possui, não precisa de aprovação. Caso seja nova solicitação, acionar Rafael Martinez @triagem psc",
        "comercial_approver": "Rafael Martinez",
        "ops": "-",
        "ops_approver": None,
    },
    "Exclusividade de fornecimento - Escola": {
        "comercial": "Se escola já possui, não precisa de aprovação. Caso seja nova solicitação, acionar Rafael Martinez @triagem psc",
        "comercial_approver": "Rafael Martinez",
        "ops": "-",
        "ops_approver": None,
    },
    "Modalidade de venda - alteração (B2C x B2B x B2B2B)": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Verificar dívida interna: até R$ 50k aprovação automática; acima disso marcar Rafael Bae (SLA 2 dias úteis) @triagem--contratos psc",
        "ops_approver": "Rafael Bae",
        "check_debt": True,
    },
    "Pagamento de multa do concorrente": {
        "comercial": "Líder direto do consultor",
        "comercial_approver": "LIDER_DIRETO",
        "ops": "-",
        "ops_approver": None,
    },
    "Falta de comprovante/dados bancários": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Simulador - Inviabilidade ampliação": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Simulador - Inviabilidade contrato": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "-",
        "ops_approver": None,
    },
    "Simulador - redução > 10% de alunado": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Ampliação de série programada automática": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Visitas Pedagógicas - Quantidade Personalizada": {
        "comercial": "Se escola já possui, não precisa de aprovação. Caso nova solicitação, acionar Rafael Martinez @triagem psc",
        "comercial_approver": "Rafael Martinez",
        "ops": "-",
        "ops_approver": None,
    },
    "Bundle Incentivado 2027": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Comercial - Campanha Comercial": {
        "comercial": "Líder direto do consultor",
        "comercial_approver": "LIDER_DIRETO",
        "ops": "-",
        "ops_approver": None,
    },
    "Data de Pedido - Diferente do Padrão": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Thibaut Frederic Choukroun",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Pedido mínimo < 80% - Série/Ano": {
        "comercial": "Sem necessidade de aprovação no momento (Para cálculo sobre Série/Ano)",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Pedido mínimo < 80% - Total Global": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Thibaut Frederic Choukroun",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Escola retira material no CD": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Se escola já possui em contrato -> Aprovação automática; caso contrário, aprovação do Thibaut @triagem psc",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Data de entrega - Diferente do Padrão": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Lucas Alves Ramos",
        "ops_approver": "Lucas Alves Ramos",
    },
    "Devolução > 10% - Série/Ano": {
        "comercial": "Sem necessidade de aprovação no momento (Para cálculo sobre Série/Ano)",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Devolução > 10% - Total Global": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Se escola já possui em contrato -> Aprovação automática; caso contrário, aprovação do Thibaut @triagem psc",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Devolução V1 - Data diferente do padrão (15/03)": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Se escola já possui em contrato -> Aprovação automática; caso contrário, aprovação do Thibaut @triagem psc",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Capa Personalizada - Envio Principal": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Lucas Alves Ramos",
        "ops_approver": "Lucas Alves Ramos",
    },
    "Kit personalizado": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Lucas Alves Ramos",
        "ops_approver": "Lucas Alves Ramos",
    },
    "Material opcional sem principal": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "Ingrid Mariana De Souza Costa",
        "ops_approver": "Ingrid Mariana De Souza Costa",
    },
    "Kit Professor - Quantidade Personalizada": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Se escola já possui em contrato -> Aprovação automática; caso contrário, aprovação do Thibaut @triagem psc",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Material Adaptado - Ampliado": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Ingrid Mariana De Souza Costa",
        "ops_approver": "Ingrid Mariana De Souza Costa",
    },
    "Material Adaptado - Braile": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Ingrid Mariana De Souza Costa",
        "ops_approver": "Ingrid Mariana De Souza Costa",
    },
    "Reajuste por Índice": {
        "comercial": "Líder direto do consultor",
        "comercial_approver": "LIDER_DIRETO",
        "ops": "-",
        "ops_approver": None,
    },
    "Incentivo Comercial para inadimplentes": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Dívida até R$ 50k é aprovação automática; acima disso, acionar Rafael Bae (SLA: 2 dias úteis)",
        "ops_approver": "Rafael Bae",
        "check_debt": True,
    },
    "Incentivo Comercial - Padrão": {
        "comercial": "Aprovação necessária apenas se incentivo > 20% do ACV (N3 - Chalfun/Faleiros) @triagem psc",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "-",
        "ops_approver": None,
    },
    "Incentivo Comercial - Antecipação Pagamento": {
        "comercial": "Aprovação comercial necessária se incentivo > 20% do ACV (N3 - Chalfun/Faleiros) @triagem psc",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "Se pagamento anterior a 60 dias após assinatura precisa de aprovação de Aline Del Pezzo @triagem",
        "ops_approver": "Aline Del Pezzo",
    },
    "Incentivo Comercial - Por Atingimento": {
        "comercial": "Necessário adequar ao modelo cadastrado no PIC (3 faixas)",
        "comercial_approver": None,
        "ops": "Gleidson Oliveira",
        "ops_approver": "Gleidson Oliveira",
    },
    "Alteração Foro - Não Capitais": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Thais Teixeira De Oliveira Rego",
        "ops_approver": "Thais Teixeira De Oliveira Rego",
    },
    "Incentivo Comercial - Abatimento de Dívida": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Dívida até R$ 50k aprovação automática; acima disso, acionar Rafael Bae (SLA: 2 dias úteis)",
        "ops_approver": "Rafael Bae",
        "check_debt": True,
    },
    "Repasse - Antecipação de pagamento": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Luani Bissi / Matheus Alves Rocha",
        "ops_approver": "Luani Bissi",
    },
    "Repasse - Apuração fora da janela padrão": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Luani Bissi",
        "ops_approver": "Luani Bissi",
    },
    "Repasse - cálculo não padrão": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Luani Bissi",
        "ops_approver": "Luani Bissi",
    },
    "Repasse - Filantrópica": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Repasse - Pagamento Matriz (Rede)": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Repasse - Sem pagamento de Repasse": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Reembolso de crédito de devolução": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "Gleidson Oliveira",
        "ops_approver": "Gleidson Oliveira",
    },
    "Chromebook - Envios extras de chromebook": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Rafael Soares Da Silva",
        "ops_approver": "Rafael Soares Da Silva",
    },
    "Multa rescisória < 50%": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "Entre 50% e 30% sem aprovação; abaixo de 30% aprovador é Rafael Bae @triagem psc",
        "ops_approver": "Rafael Bae",
    },
    "Multa rescisória - Isenção": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "Rafael Bae (SLA 2 dias úteis). @triagem verificar se 1. Exceção já existente / 2. Outras unidades possuem exceção",
        "ops_approver": "Rafael Bae",
    },
    "Encerramento e Penalidades - No Go": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "-",
        "ops_approver": None,
    },
    "Comercial - Não Formação de Turma": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "Thibaut Frederic Choukroun",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Redução de Vigência": {
        "comercial": "N3 - Direto do Chalfun/Faleiros",
        "comercial_approver": "N3 - Direto do Chalfun/Faleiros",
        "ops": "-",
        "ops_approver": None,
    },
    "Renovação automática - Retirada": {
        "comercial": "Líder direto do consultor",
        "comercial_approver": "LIDER_DIRETO",
        "ops": "-",
        "ops_approver": None,
    },
    "Rescisão Parcial - Diminuição de séries": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Alteração LGPD": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Bianca Assone Rodrigues",
        "ops_approver": "Bianca Assone Rodrigues",
    },
    "CNPJ sem CNAE de educação - Escola da Base": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Livia Goia De Araujo Rossi",
        "ops_approver": "Livia Goia De Araujo Rossi",
    },
    "CNPJ sem CNAE de educação - Nova Escola": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Livia Goia De Araujo Rossi",
        "ops_approver": "Livia Goia De Araujo Rossi",
    },
    "Simulador - Vigência": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Bonificação - Kit Matrícula / Material de Campanha": {
        "comercial": "Não precisa de aprovação",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
    "Prazo de conferência de material (dias)": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Thibaut Frederic Choukroun",
        "ops_approver": "Thibaut Frederic Choukroun",
    },
    "Prazo para pagamento de repasse (dias)": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Luani Bissi",
        "ops_approver": "Luani Bissi",
    },
    "% Multa/Juros Inadimplência": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Maria Julia Pagani Fazano",
        "ops_approver": "Maria Julia Pagani Fazano",
    },
    "Condições de Pagamento e Parcelamento - Fora do padrão": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Nath Nobre",
        "ops_approver": "Nath Nobre",
    },
    "Suspensão Condicional de Multa - Contrato Anterior (Churn 0)": {
        "comercial": "Rhayam Oliveira Nascimento",
        "comercial_approver": "Rhayam Oliveira Nascimento",
        "ops": "Verificar dívida interna: até R$ 50k aprovação automática; acima disso marcar Rafael Bae (SLA 2 dias úteis) @triagem--contratos psc",
        "ops_approver": "Rafael Bae",
        "check_debt": True,
    },
    "Chromebook - Aumento da vigência de comodato": {
        "comercial": "Rafael De Simone Martines",
        "comercial_approver": "Rafael De Simone Martines",
        "ops": "-",
        "ops_approver": None,
    },
    "Modalidade diferente da Análise de Crédito (B2C x B2B)": {
        "comercial": "-",
        "comercial_approver": None,
        "ops": "Rafael Bae (SLA 2 dias) @triagem verificar se consultor forneceu link da thread de Análise de Crédito",
        "ops_approver": "Rafael Bae",
    },
    "Preço de Ponta B2C SAS": {
        "comercial": "Ana Beatriz Do Vale Silva e Carla Beatriz Catunda Fernandes",
        "comercial_approver": "Ana Beatriz Do Vale Silva",
        "ops": "-",
        "ops_approver": None,
    },
    "N/A": {
        "comercial": "Não aplicável",
        "comercial_approver": None,
        "ops": "-",
        "ops_approver": None,
    },
}

ALL_EXCEPTIONS_LIST = list(EXCEPTIONS_RULES.keys())
